flow-indexer-api:
  resources:
    jvm:
      xmx_megabytes: 768
      max_direct_memory_megabytes: 256

flow-indexer-listener:
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 512
