flow-indexer-backend-api:
  image:
    repository: flow-nft-indexer-backend-api
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.appEnv" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.appEnv" $ }}/flow-indexer'
    SPRING_PROFILES_ACTIVE: '{{ include "service.appEnv" $ }},consul'
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 64
  # updateConfig:
  #   order: start-first
  networks:
    common:
    - '{{ include "service.appEnv" $ }}-backend'
    additional:
    - proxy-staging

flow-indexer-scanner:
  image:
    repository: flow-nft-indexer-scanner
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.appEnv" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.appEnv" $ }}/flow-indexer'
    SPRING_PROFILES_ACTIVE: '{{ include "service.appEnv" $ }},consul'
  resources:
    jvm:
      xmx_megabytes: 400
      max_direct_memory_megabytes: 32
  networks:
    common: 
    - '{{ include "service.appEnv" $ }}-backend'
    - internet