flow-indexer-backend-api:
  image:
    repository: flow-nft-indexer-backend-api
  service:
    enabled: true
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "app.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "app.env" $ }}/flow-indexer'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "app.env" $ }}'
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 64

flow-indexer-scanner:
  image:
    repository: flow-nft-indexer-scanner
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "app.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "app.env" $ }}/flow-indexer'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "app.env" $ }}'
  priorityClassName: high
  resources:
    jvm:
      xmx_megabytes: 400
      max_direct_memory_megabytes: 32
