flow-indexer-api:
  replicas: 2
  image:
    repository: flow-indexer-api
  service:
    enabled: true
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "app.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "app.env" $ }}/flow-indexer'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "app.env" $ }}'
  resources:
    jvm:
      xmx_megabytes: 368
      max_direct_memory_megabytes: 32

flow-indexer-listener:
  replicas: 1
  image:
    repository: flow-indexer-listener
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "app.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "app.env" $ }}/flow-indexer'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "app.env" $ }}'
  priorityClassName: high
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 512
