spring:
  application:
    name: flow-nft-indexer-api
  data:
    mongodb:
      auto-index-creation: true

flow-indexer-api:
  chain-id: TESTNET
  flow-access-url:
  flow-access-port:

application:
  service-name: flow-nft-indexer-api
