spring:
  application:
    name: flow-nft-indexer-api
  data:
    mongodb:
      auto-index-creation: true

flow-indexer-api:
  flow-access-url:
  flow-access-port:

application:
  service-name: flow-nft-indexer-api

rarible:
  core:
    apm:
      agent:
        enabled: true
        server: http://elk_apm-server:8200
        packages: org.rarible.flow.api