spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}
  config:
    use-legacy-processing: true
    import: "consul:"

  cloud:
    bootstrap:
      enabled: true

flow-indexer-api:
  kafka-replica-set: ${kafka.hosts}