logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG

spring:
  cloud:
    consul:
      discovery:
        tags:
          - web-api:flow-api-dev.rarible.com
          - api-location:/flow/api

rarible:
  core:
    filter:
      cors:
        enabled: true
