spring:
  application:
    name: flow-scanner

application:
  environment: dev

logging:
  level:
    com.rarible.flow: DEBUG


scanner:
  environment: dev
  kafka-replica-set: ${kafka.hosts}
  alchemy-api-key: 6k9n3u0syeas3u47ezlpxhlzfu666egf
#  alchemy-api-key: t6y8505dtycu8dbz5p7rp3f1gb4a992e
#  alchemy-api-key: 9huh0gjb1ftvd7h9s3vnuptfvys4yqrw

blockchain:
  scanner:
    flow:
      chainId: MAINNET
      poller:
        delay: 300
      job:
        reconciliation:
          batchSize: 250
      blockBufferSize: 128
grpc:
  client:
    flow:
      address: dns:///flow-mainnet.g.alchemy.com:443
      enable-keep-alive: true
