application:
  environment: staging

logging:
  level:
    com.rarible.flow: DEBUG

blockchain:
  scanner:
    flow:
      chainId: TESTNET
      poller:
        delay: 100
      job:
        reconciliation:
          enabled: true

app:
  environment: staging
  kafka-replica-set: ${kafka.hosts}
  chain-id: TESTNET

flow-api:
  flow-access-url: "access.devnet.nodes.onflow.org"
  flow-access-port: 9000
  chain-id: TESTNET

