application:
  environment: prod

blockchain:
  scanner:
    flow:
      chainId: MAINNET
      poller:
        delay: 200

scanner:
  environment: prod
  kafka-replica-set: ${kafka.hosts}

spring:
  profiles:
    active: onlyscanner
  data:
    mongodb:
      uri: mongodb://${mongodb.user}:${mongodb.password}@${mongodb.hosts}
      database: ${mongodb.database}
