spring:
  application:
    name: flow-scanner

application:
  environment: dev

logging:
  level:
    com.rarible.flow: DEBUG

app:
  environment: dev
  chain-id: TESTNET
  kafka-replica-set: ${kafka.hosts}

blockchain:
  scanner:
    flow:
      chainId: TESTNET
      poller:
        delay: 100
      job:
        reconciliation:
          batchSize: 25
      retryPolycy:
        scan:
          maxProcessTime: 1m
