spring:
  data:
    mongodb:
      uri: "mongodb://10.10.11.22:47017" #${mongodb.hosts}
      database: dev-flow-scanner #${mongodb.database}
  config:
    import: "consul:"

  jmx:
    enabled: false
  cloud:
    service-registry:
      auto-registration:
        enabled: true
    consul:
      discovery:
        health-check-path: /_status/ping
        health-check-critical-timeout: "3m"
      host: consul-agent
      port: 8500
      config:
        watch:
          enabled: false
        enabled: true
        prefix:

scanner:
  kafka-replica-set: "staging-kafka-1:9092" #${kafka.hosts}
