spring:
  application:
    name: flow-scanner

  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
    main:
      banner-mode: log
      web-application-type: reactive

