application:
  environment: prod

blockchain:
  scanner:
    flow:
      chainId: MAINNET
      poller:
        delay: 100
      job:
        reconciliation:
          batchSize: 1000

scanner:
  environment: prod
  kafka-replica-set: ${kafka.hosts}
  default-item-collection:
    id: "A.665b9acf64dfdfdb.CommonNFT.NFT"
    owner: "0xe91e497115b9731b"
    name: "CommonNFT"
    symbol: "CNFT"
spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.user}:${mongodb.password}@${mongodb.hosts}
      database: ${mongodb.database}
management:
  endpoint:
    metrics:
      enabled: true
