application:
  environment: staging

logging:
  level:
    com.rarible.flow: DEBUG

blockchain:
  scanner:
    flow:
      poller:
        delay: 200
      job:
        reconciliation:
          enabled: false

scanner:
  environment: dev
  kafka-replica-set: ${kafka.hosts}

  tracked-contracts:
    - "e7e97b10fbd3b607" #Rari Staging

  sporks:
    -
      name: "Devnet25"
      nodeUrl: "access.devnet.nodes.onflow.org:9000"
      firstBlockHeight: 41567027
