spring:
  application:
    name: flow-scanner

application:
  environment: dev

logging:
  level:
    com.rarible.flow: DEBUG


scanner:
  environment: dev
  kafka-replica-set: ${kafka.hosts}

blockchain:
  scanner:
    flow:
      chainId: TESTNET
      poller:
        delay: 100
      job:
        reconciliation:
          batchSize: 10000
