spring:
  application:
    name: flow-scanner
  data:
    mongodb:
      auto-index-creation: true
mongock:
  runner-type: applicationrunner
  migration-scan-package: "com.rarible.flow.scanner.migrations"
  default-migration-author: "flow"

rarible:
  core:
    apm:
      agent:
        enabled: true
        server: http://elk_apm-server:8200
        packages: org.rarible.flow.indexer
