application:
  environment: staging

logging:
  level:
    com.rarible.flow: DEBUG

blockchain:
  scanner:
    flow:
      chainId: TESTNET
      poller:
        delay: 100
      job:
        reconciliation:
          enabled: false

app:
  environment: staging
  kafka-replica-set: ${kafka.hosts}
  chain-id: TESTNET


