application:
  environment: dev
scanner:
  environment: dev
  kafka-replica-set: ${kafka.hosts}


logging:
  level:
    com.rarible.flow: DEBUG

blockchain:
  scanner:
    flow:
      poller:
        delay: 200
