spring:
  application:
    name: flow-scanner

application:
  environment: dev

logging:
  level:
    com.rarible.flow: DEBUG


scanner:
  environment: dev
  kafka-replica-set: ${kafka.hosts}
  default-item-collection:
    id: "A.ebf4ae01d1284af8.RaribleNFT.NFT"
    owner: "0xe91e497115b9731b"
    name: "RaribleNFT"
    symbol: "RNFT"

blockchain:
  scanner:
    flow:
      chainId: TESTNET
      poller:
        delay: 100
      job:
        reconciliation:
          batchSize: 1000
