application:
  environment: staging

logging:
  level:
    com.rarible.flow: DEBUG

blockchain:
  scanner:
    flow:
      chainId: TESTNET
      poller:
        delay: 100
      job:
        reconciliation:
          enabled: false

scanner:
  environment: staging
  kafka-replica-set: ${kafka.hosts}
  default-item-collection:
    id: "A.665b9acf64dfdfdb.CommonNFT.NFT"
    owner: "0xe91e497115b9731b"
    name: "CommonNFT"
    symbol: "CNFT"


