spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: flow-${spring.profiles.active}
  cloud:
    bootstrap:
      enabled: false

scanner:
  kafka-replica-set: PLAINTEXT://localhost:29092
logging:
  level:
    com.rarible.blockchain.scanner.flow.FlowNetNewBlockPoller: debug
  logstash:
    tcp-socket:
      enabled: false

rarible:
  core:
    apm:
      annotation:
        enabled: false

application:
  environment: dev

app:
  environment: dev
  chain-id: MAINNET
  kafka-replica-set: http://localhost:29092
  web-api-url: http://localhost:8080

flow-api:
  service-account:
    address: "0xebf4ae01d1284af8"
    private-key: "c9c26ffea639ac653130127a6fdba7448d7752aadb26c9027accd504b2b7bcd3"
