application:
  environment: prod

blockchain:
  scanner:
    flow:
      chainId: MAINNET
      poller:
        delay: 500
      job:
        reconciliation:
          batchSize: 250
        blockBufferSize: 128

scanner:
  environment: prod
  kafka-replica-set: ${kafka.hosts}
  alchemy-api-key: 9huh0gjb1ftvd7h9s3vnuptfvys4yqrw

spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.user}:${mongodb.password}@${mongodb.hosts}
      database: ${mongodb.database}
management:
  endpoint:
    metrics:
      enabled: true
grpc:
  client:
    flow:
      address: dns:///flow-mainnet.g.alchemy.com:443
      enable-keep-alive: true
