application:
  environment: staging

logging:
  level:
    com.rarible.flow: DEBUG

blockchain:
  scanner:
    flow:
      chainId: TESTNET
      poller:
        delay: 100
      job:
        reconciliation:
          enabled: false

scanner:
  environment: dev
  kafka-replica-set: ${kafka.hosts}

  tracked-contracts:
    - "e7e97b10fbd3b607" #Rari Staging
  listenAllEvents: true
  subscribeAllEvents: false
