spring:
  application:
    name: flow-scanner

application:
  environment: dev

logging:
  level:
    com.rarible.flow: DEBUG

app:
  environment: dev
  chain-id: MAINNET
  kafka-replica-set: ${kafka.hosts}

blockchain:
  scanner:
    flow:
      chainId: MAINNET
      poller:
        delay: 100
      job:
        reconciliation:
          batchSize: 1000
