application:
  environment: prod

blockchain:
  scanner:
    flow:
      chainId: MAINNET
      poller:
        delay: 100
      job:
        reconciliation:
          batchSize: 250

scanner:
  environment: prod
  kafka-replica-set: ${kafka.hosts}
  default-item-collection:
    id: "A.ebf4ae01d1284af8.RaribleNFT.NFT"
    owner: "0xebf4ae01d1284af8"
    name: "RaribleNFT"
    symbol: "RNFT"
spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.user}:${mongodb.password}@${mongodb.hosts}
      database: ${mongodb.database}
management:
  endpoint:
    metrics:
      enabled: true
