application:
  environment: prod

blockchain:
  scanner:
    flow:
      chainId: MAINNET
      poller:
        delay: 500
      job:
        reconciliation:
          batchSize: 2500
        blockBufferSize: 128

scanner:
  environment: prod
  kafka-replica-set: ${kafka.hosts}

spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.user}:${mongodb.password}@${mongodb.hosts}
      database: ${mongodb.database}
management:
  endpoint:
    metrics:
      enabled: true
