spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: flow-${spring.profiles.active}

scanner:
  kafka-replica-set: PLAINTEXT://localhost:29092
logging:
  level:
    com.rarible.blockchain.scanner.flow.FlowNetNewBlockPoller: debug
  logstash:
    tcp-socket:
      enabled: false

flow-api:
  service-account:
    address: "0xebf4ae01d1284af8"
    private-key: "c9c26ffea639ac653130127a6fdba7448d7752aadb26c9027accd504b2b7bcd3"
