spring:
  data:
    mongodb:
      uri: mongodb://mongodb/flow-${spring.profiles.active}
      database: flow-${spring.profiles.active}

scanner:
  kafka-replica-set: PLAINTEXT://staging-kafka-1:9092 #${kafka.hosts}
