spring:
  application:
    name: flow-scanner

application:
  environment: dev

logging:
  level:
    com.rarible.flow: DEBUG


scanner:
  environment: dev
  kafka-replica-set: ${kafka.hosts}
  alchemy-api-key: t6y8505dtycu8dbz5p7rp3f1gb4a992e

blockchain:
  scanner:
    flow:
      chainId: TESTNET
      poller:
        delay: 300
      job:
        reconciliation:
          batchSize: 250
      blockBufferSize: 128
grpc:
  client:
    flow:
      address: dns:///flow-testnet.g.alchemy.com:443
      enable-keep-alive: true
