application:
  environment: prod

blockchain:
  scanner:
    flow:
      chainId: MAINNET
      poller:
        delay: 200

scanner:
  environment: prod
  kafka-replica-set: ${kafka.hosts}

spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}
      username: ${mongodb.user}
      password: ${mongodb.password}
  profiles:
    active: consul,prod,onlyscanner
