grpc:
  client:
    flow:
      address: access.devnet.nodes.onflow.org:9000

scanner:
  tracked-contracts:
    - "9a0766d93b6608b7" #FungibleToken
    - "d07a7fa848ee5a9b" #Kibble KittyItems KittyItemsMarket
    - "9837bf0b0b963a4a" #Versus Auction
    - "0b601b730796f30e" #Versus Auction (FUSD)
    - "e3750a9bc4137f3f" #Disrupt Now
    - "877931736ee77cff" #TopShot
    - "547f177b243b4d80" #MarketTopShot
    - "bf7e7e84ad6d8b29" #ChessCombo
    - "5c9fd048deb56cd4" #Veolet
    - "2695ea898b04f0c0" #marketplace unknown
    - "a6f77977aca4f3ac" #MotoGP
    - "ff1201e3a53ee578" #Rari
    - "fcfb23c627a63d40" #Rari 1-phase mint
    - "e91e497115b9731b" #Rari

  sporks:
    -
      name: "Devnet25"
      nodeUrl: "access.devnet.nodes.onflow.org:9000"
      firstBlockHeight: 39272449
