application:
  environment: prod

blockchain:
  scanner:
    flow:
      chainId: MAINNET
      poller:
        delay: 200

scanner:
  environment: prod
  kafka-replica-set: ${kafka.hosts}

spring:
  data:
    mongodb:
      username: ${mongodb.user}
      password: ${mongodb.password}
