blockchain:
  scanner:
    flow:
      chainId: TESTNET
      poller:
        delay: 100


scanner:
  tracked-contracts:
    - "ff1201e3a53ee578" #Rari
    - "fcfb23c627a63d40" #Rari 1-phase mint
    - "665b9acf64dfdfdb" #Rari
