spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.user}:${mongodb.password}@${mongodb.hosts}
      database: ${mongodb.database}
  cloud:
    consul:
      discovery:
        tags:
          - web-api:flow-api.rarible.org

management:
  endpoint:
    metrics:
      enabled: true

rarible:
  core:
    filter:
      cors:
        enabled: true

flow-indexer-api:
  flow-access-url: "access.mainnet.nodes.onflow.org"
  flow-access-port: 9000
  chain-id: MAINNET

app:
  flow-access-url: "access.mainnet.nodes.onflow.org"
  flow-access-port: 9000
  environment: prod
  kafka-replica-set: ${kafka.hosts}
  chain-id: MAINNET
  web-api-url: ${web-api-url}

application:
  environment: prod
