spring:
  application:
    name: flow-indexer-api
  data:
    mongodb:
      auto-index-creation: false

flow-indexer-api:
  flow-access-url:
  flow-access-port:
  alchemy-api-key: ${alchemy.api.key}
  ipfs:
    internalGateway: "https://ipfs.io"
    publicGateway: "https://ipfs.io"

app:
  flow-access-url:
  flow-access-port:

application:
  service-name: flow-indexer-api

blockchain:
  scanner:
    flow:
      scan:
        enabled: false
      monitoring:
        enabled: false
      task:
        reindex:
          enabled: false
