spring:
  application:
    name: flow-indexer-api
  data:
    mongodb:
      auto-index-creation: false

flow-indexer-api:
  flow-access-url:
  flow-access-port:
  alchemy-api-key: ${alchemy.api.key}
  ipfs:
    internalGateway: "https://ipfs.io"
    publicGateway: "https://ipfs.io"

app:
  flow-access-url:
  flow-access-port:

application:
  service-name: flow-indexer-api

rarible:
  core:
    apm:
      agent:
        enabled: true
        server: http://elk_apm-server:8200
        packages: org.rarible.flow.api
      web:
        filter:
          enabled: true
      annotation:
        enabled: true

blockchain:
  scanner:
    flow:
      scan:
        enabled: false
      monitoring:
        enabled: false
      task:
        reindex:
          enabled: false
