application:
  environment: prod

blockchain:
  scanner:
    flow:
      chainId: MAINNET
      poller:
        delay: 100
      job:
        reconciliation:
          batchSize: 250
      retryPolicy:
        scan:
          maxProcessTime: 10m
app:
  environment: prod
  kafka-replica-set: ${kafka.hosts}
  chain-id: MAINNET
  web-api-url: ${web-api-url}
  featureFlags:
    enableRaribleCard: false
    enableRariblePack: false
    enableRaribleNft: false
    enableStorefrontV1: false
    enableStorefrontV2: false

spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.user}:${mongodb.password}@${mongodb.hosts}
      database: ${mongodb.database}
management:
  endpoint:
    metrics:
      enabled: true

logging:
  level:
    com.rarible.flow: DEBUG

flow-api:
  flow-access-url: "access.mainnet.nodes.onflow.org"
  flow-access-port: 9000
  chain-id: MAINNET
  cleanup:
    enabled: true
    preservedCollections: "A.01ab36aaf654a13e.RaribleNFT"
