app:
  environment: ${application.environment}
  chain-id: TESTNET
  kafka-replica-set: ${kafka.host}
  web-api-url: http://local-flow-indexer-api:8080

flow-api:
  flow-access-url: "access.devnet.nodes.onflow.org"
  flow-access-port: 9000
  chain-id: ${app.chain-id}
  service-account:
    address: "0xebf4ae01d1284af8"
    private-key: "c9c26ffea639ac653130127a6fdba7448d7752aadb26c9027accd504b2b7bcd3"


blockchain:
  scanner:
    flow:
      chainId: ${app.chain-id}
      scan:
        firstAvailableBlock: 95808975
