spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: flow-${spring.profiles.active}
  cloud:
    bootstrap:
      enabled: false

    loadbalancer:
      cache:
        enabled: false

logging:
  logstash:
    tcp-socket:
      enabled: false
      destinations: []

application:
  environment: dev

app:
  environment: dev
  chain-id: TESTNET
  kafka-replica-set: http://localhost:29092
  web-api-url: http://localhost:8080

flow-api:
  flow-access-url: "access.devnet.nodes.onflow.org"
  flow-access-port: 9000
  chain-id: TESTNET
  service-account:
    address: "0xebf4ae01d1284af8"
    private-key: "c9c26ffea639ac653130127a6fdba7448d7752aadb26c9027accd504b2b7bcd3"

management:
  endpoint:
    metrics:
      enabled: false

blockchain:
  scanner:
    flow:
      chainId: TESTNET
      poller:
        delay: 300
      job:
        reconciliation:
          batchSize: 25
      retryPolicy:
        scan:
          maxProcessTime: 3m
