spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}

  config:
    use-legacy-processing: true
    import: "consul:"

  cloud:
    bootstrap:
      enabled: true

    loadbalancer:
      cache:
        enabled: false

blockchain:
  scanner:
    kafka:
      broker-replica-set: ${kafka.hosts}

flow-api:
  service-account:
    address: ${service-account.address}
    private-key: ${service-account.private-key}
