application:
  environment: dev

logging:
  level:
    com.rarible.flow: DEBUG

app:
  flow-access-url: "access.devnet.nodes.onflow.org"
  flow-access-port: 9000
  environment: dev
  chain-id: TESTNET
  kafka-replica-set: ${kafka.hosts}
  web-api-url: ${web-api-url}

flow-api:
  flow-access-url: "access.devnet.nodes.onflow.org"
  flow-access-port: 9000
  chain-id: TESTNET
  web-api-url: ${web-api-url}

blockchain:
  scanner:
    flow:
      chainId: TESTNET
      poller:
        delay: 300
      job:
        reconciliation:
          enabled: false
          batchSize: 25
      retryPolicy:
        scan:
          maxProcessTime: 1m
