spring:
  application:
    name: flow-indexer-listener
  data:
    mongodb:
      auto-index-creation: false


mongock:
  change-logs-scan-package:
    - com.rarible.flow.scanner.migrations
    - com.rarible.blockchain.scanner.flow.migration

jobs:
  order-price-update:
    enabled: false
    rate: 120000

app:
  featureFlags:
    enableBarbieCard: true
    enableBarbiePack: true
    enableBarbieToken: true
    enableHwOtherCard: true
    enableHwOtherCardV2: true
    enableRaribleCard: false
    enableRaribleCardV2: false
    enableRaribleCardV2Meta: true
    enableRariblePack: false
    enableRariblePackV2: false
    enableRaribleNft: false
    enableStorefrontV1: false
    enableRaribleBarbieCard: false
    enableRaribleBarbiePack: false
    enableRaribleBarbieToken: false

blockchain:
  scanner:
    kafka:
      numberOfPartitionsPerLogGroup: 18
    flow:
      optimisticLockRetries: 5
      retry-policy:
        scan:
          reconnect-delay: 2s
        client:
          delay: 2s
      scan:
        batchLoad:
          batchSize: 5
      monitoring:
        enabled: true
        rootPath: "protocol.flow.indexer"
        timestampUnit: millisecond
        worker:
          pollingPeriod: 1m
      task:
        reindex:
          enabled: true
