blockchain:
  scanner:
    flow:
      poller:
        delay: 100

app:
  featureFlags:
    enableHwOtherCard: false
    enableHwOtherCardV2: false
    enableBarbiePack: false
    enableRaribleCard: false
    enableRaribleCardV2: false
    enableRaribleCardV2Meta: false
    enableRariblePack: false
    enableRariblePackV2: false
    enableRaribleNft: false
    enableRaribleBarbieCard: false
    enableRaribleBarbiePack: false
    enableRaribleBarbieToken: false
    enableStorefrontV1: false

flow-api:
  cleanup:
    enabled: true