spring:
  application:
    name: flow-indexer-listener
  data:
    mongodb:
      auto-index-creation: false


mongock:
  change-logs-scan-package:
    - com.rarible.flow.scanner.migrations

rarible:
  core:
    apm:
      agent:
        enabled: false
        server: http://elk_apm-server:8200
        packages: org.rarible.flow.indexer

jobs:
  order-price-update:
    enabled: false
    rate: 120000

blockchain:
  scanner:
    kafka:
      numberOfPartitionsPerLogGroup: 18
    flow:
      optimisticLockRetries: 5
      retry-policy:
        scan:
          reconnect-delay: 2s
        client:
          delay: 2s
      scan:
        batchLoad:
          batchSize: 5
      monitoring:
        enabled: true
        rootPath: "protocol.flow.indexer"
        timestampUnit: millisecond
        worker:
          pollingPeriod: 1m
      task:
        reindex:
          enabled: true
