application:
  environment: staging

logging:
  level:
    com.rarible.flow: DEBUG

blockchain:
  scanner:
    flow:
      chainId: TESTNET
      poller:
        delay: 100
      job:
        reconciliation:
          batchSize: 25
        retryPolicy:
          scan:
            maxProcessTime: 1m

app:
  flow-access-url: "access.devnet.nodes.onflow.org"
  flow-access-port: 9000
  environment: staging
  kafka-replica-set: ${kafka.hosts}
  chain-id: TESTNET
  web-api-url: ${web-api-url}

flow-api:
  flow-access-url: "access.devnet.nodes.onflow.org"
  flow-access-port: 9000
  chain-id: TESTNET


