grpc:
  client:
    flow:
      address: access.devnet.nodes.onflow.org:9000

scanner:
  tracked-contracts:
    - "ff1201e3a53ee578" #Rari
    - "fcfb23c627a63d40" #Rari 1-phase mint
    - "e91e497115b9731b" #Rari

