package com.rarible.flow.core.domain

enum class FlowLogType {
    MINT,
    WITHDRAW,
    DEPOSIT,
    BURN,
    LISTING_AVAILABLE,
    LISTING_COMPLETED,
    BID_AVAILABLE,
    BID_COMPLETED,
    CUSTOM,
    LOT_AVAILABLE,
    LOT_COMPLETED,
    LOT_END_TIME_CHANGED,
    LOT_CLEANED,
    OPEN_BID,
    CLOSE_BID,
    INCREASE_BID,
    COLLECTION_MINT,
    COLLECTION_DEPOSIT,
    COLLECTION_WITHDRAW,
    COLLECTION_BURN,
    COLLECTION_CHANGE,
    ADMIN_MINT_CARD
}
