spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}
  config:
    import: "consul:consul-agent"

flow-indexer-listener:
  kafka-replica-set: ${kafka.hosts}