application:
  environment: dev
flow-indexer-listener:
  environment: dev
  default-item-collection:
    id: "A.665b9acf64dfdfdb.CommonNFT.NFT"
    owner: "0xe91e497115b9731b"
    name: "CommonNFT"
    symbol: "CNFT"